weights: ''''''
cfg: models/detect/yolov9-c.yaml
data: data/placas.yaml
hyp:
  lr0: 0.012
  lrf: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 5.0
  warmup_momentum: 0.85
  warmup_bias_lr: 0.1
  box: 8.5
  cls: 1.3
  cls_pw: 1.0
  obj: 1.7
  obj_pw: 1.0
  dfl: 1.7
  iou_t: 0.35
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.8
  hsv_v: 0.6
  degrees: 5.0
  translate: 0.15
  scale: 0.8
  shear: 2.0
  perspective: 0.001
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.12
  copy_paste: 0.0
epochs: 400
batch_size: 4
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: disk
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 1
project: runs/placas
name: v9m-placas_fromscratch_v6
exist_ok: false
quad: false
cos_lr: true
flat_cos_lr: false
fixed_lr: false
label_smoothing: 0.07
patience: 150
freeze:
- 0
save_period: 10
seed: 0
local_rank: -1
min_items: 0
close_mosaic: 100
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\placas\v9m-placas_fromscratch_v6
