weights: runs/placas/v9s-placas_5hyp2/weights/best_converted.pt
cfg: models/detect/yolov9-s.yaml
data: data/placas.yaml
hyp:
  lr0: 0.0015
  lrf: 0.0003
  momentum: 0.95
  weight_decay: 0.00055
  warmup_epochs: 4.0
  warmup_momentum: 0.86
  warmup_bias_lr: 0.1
  box: 8.5
  cls: 1.1
  cls_pw: 1.0
  obj: 1.4
  obj_pw: 1.0
  dfl: 1.6
  iou_t: 0.3
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.5
  hsv_v: 0.3
  degrees: 1.5
  translate: 0.06
  scale: 0.35
  shear: 0.0
  perspective: 0.001
  flipud: 0.0
  fliplr: 0.0
  mosaic: 0.45
  mixup: 0.02
  copy_paste: 0.0
epochs: 150
batch_size: 10
imgsz: 704
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 2
project: runs/placas
name: v9s-placas_b10_704_finetune
exist_ok: false
quad: false
cos_lr: true
flat_cos_lr: false
fixed_lr: false
label_smoothing: 0.07
patience: 50
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
min_items: 0
close_mosaic: 10
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\placas\v9s-placas_b10_704_finetune5
